In [7]:
import sqlalchemy
import pandas
import server.model.connection as smc

In [10]:
sql = sqlalchemy.text("SELECT * FROM information_schema.tables "
           "WHERE table_schema = 'public';")
conn = smc.engine.connect()
tbls = pandas.read_sql(sql, conn)
tbls

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action
0,scouting,public,attempts,BASE TABLE,None,None,None,None,None,YES,NO,None
1,scouting,public,dates,BASE TABLE,None,None,None,None,None,YES,NO,None
2,scouting,public,events,BASE TABLE,None,None,None,None,None,YES,NO,None
3,scouting,public,levels,BASE TABLE,None,None,None,None,None,YES,NO,None
4,scouting,public,games,BASE TABLE,None,None,None,None,None,YES,NO,None
5,scouting,public,matches,BASE TABLE,None,None,None,None,None,YES,NO,None
6,scouting,public,match_results,BASE TABLE,None,None,None,None,None,YES,NO,None
7,scouting,public,measuretypes,BASE TABLE,None,None,None,None,None,YES,NO,None
8,scouting,public,phases,BASE TABLE,None,None,None,None,None,YES,NO,None
9,scouting,public,alliances,BASE TABLE,None,None,None,None,None,YES,NO,None
10,scouting,public,schedules,BASE TABLE,None,None,None,None,None,YES,NO,None
11,scouting,public,stations,BASE TABLE,None,None,None,None,None,YES,NO,None
12,scouting,public,status,BASE TABLE,None,None,None,None,None,YES,NO,None
13,scouting,public,task_options,BASE TABLE,None,None,None,None,None,YES,NO,None
14,scouting,public,actors,BASE TABLE,None,None,None,None,None,YES,NO,None
15,scouting,public,reasons,BASE TABLE,None,None,None,None,None,YES,NO,None
16,scouting,public,tasks,BASE TABLE,None,None,None,None,None,YES,NO,None
17,scouting,public,teams,BASE TABLE,None,None,None,None,None,YES,NO,None
18,scouting,public,measures,BASE TABLE,None,None,None,None,None,YES,NO,None

In [11]:
tbls.shape

(19, 12)